services:
  transtu-discovery-service:
    build: ./discovery-service
    container_name: transtu-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4

  transtu-config-service:
    build: ./config-service
    container_name: transtu-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://transtu-discovery-service:8761/eureka
    depends_on:
      transtu-discovery-service:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transtu
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    ports:
      - "9090:80"


  transtu-gestionaccidentsincidents-service:
    build: ./gestionAccidentsIncidents
    container_name: transtu-gestionaccidentsincidents-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://transtu-discovery-service:8761/eureka
      - CONFIG_SERVICE=http://transtu-config-service:9999
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/transtu
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      transtu-config-service:
        condition: service_healthy

  transtu-reclamation-service:
    build: ./reclamation-service
    container_name: transtu-reclamation-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://transtu-discovery-service:8761/eureka
      - CONFIG_SERVICE=http://transtu-config-service:9999
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/transtu
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      transtu-gestionaccidentsincidents-service:
        condition: service_healthy

  transtu-gateway-service:
    build: ./gateway-service
    container_name: transtu-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://transtu-discovery-service:8761/eureka
      - CONFIG_SERVICE=http://transtu-config-service:9999
    depends_on:
      transtu-config-service:
        condition: service_healthy
volumes:
  db_data:

